### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by slashsynapse** [Sago2b2t/RIP-Xulu#4]
make the source code the code, NOT the jar itself

**Comment by supakeks** [comment]
its obfuscated kek

**Comment by slashsynapse** [comment]
fuk this bitch 
![image](https://user-images.githubusercontent.com/60920165/96673642-91f07d80-1384-11eb-8ba0-760ba60e8e97.png)

**Comment by slashsynapse** [comment]
fuk this bitch 
![Uploading image.png…]()

**Comment by zispanos** [comment]
> fuk this bitch
> ![image](https://user-images.githubusercontent.com/60920165/96673642-91f07d80-1384-11eb-8ba0-760ba60e8e97.png)

you're retarded

**Comment by slashsynapse** [comment]
> you're retarded
lol never imagined you to comment
